# Generated by Django 3.0.7 on 2020-06-24 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_auto_20200614_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='John', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('usage_place', models.CharField(max_length=50)),
                ('pickup_location', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('comments', models.TextField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
