# Generated by Django 3.0.7 on 2020-06-24 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
