# Generated by Django 3.0.7 on 2020-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20200624_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
    ]
