# Generated by Django 3.0.7 on 2020-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='language',
            field=models.CharField(choices=[('', 'Sivuston nimi'), ('fi', 'Suomi'), ('ru', 'Venäjä'), ('en', 'Englanti'), ('et', 'Viro')], default='', max_length=20),
        ),
    ]
