# Generated by Django 3.0.7 on 2020-10-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_option_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='language',
            field=models.CharField(choices=[('', 'Kieli'), ('fi', 'Suomi'), ('ru', 'Venäjä'), ('en', 'Englanti'), ('et', 'Viro')], default='', max_length=20),
        ),
    ]
