# Generated by Django 3.0.7 on 2020-10-21 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20201021_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rentals.Option')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rentals.Rental')),
            ],
        ),
    ]
