# Generated by Django 3.0.7 on 2020-06-09 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img_link', models.ImageField(blank=True, upload_to='photos')),
                ('text', models.TextField(max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('news_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
