# Generated by Django 3.0.7 on 2020-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body_type',
        ),
        migrations.AddField(
            model_name='page',
            name='page_lang',
            field=models.CharField(choices=[('', 'Sivuston nimi'), ('FI', 'Suomi'), ('RU', 'Venäjä'), ('EN', 'Englanti'), ('ES', 'Viro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(choices=[('', 'Sivuston nimi'), ('AB', 'About'), ('NW', 'News'), ('CL', 'Car List'), ('CN', 'CONDITION'), ('PC', 'PRIVACY'), ('SV', 'SERVICES')], default='', max_length=20),
        ),
    ]
