# Generated by Django 3.0.7 on 2020-07-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=50)),
                ('full_description', models.TextField(max_length=200)),
                ('course_start', models.DateField(default=datetime.date.today)),
                ('course_end', models.DateField(default=datetime.date.today)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course_duration', models.DurationField()),
                ('course_image', models.ImageField(blank=True, upload_to='cars')),
            ],
        ),
    ]
