# Generated by Django 3.0.7 on 2020-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(max_length=500),
        ),
    ]
