# Generated by Django 3.0.7 on 2020-07-22 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(0)]),
        ),
    ]
