# Generated by Django 3.0.7 on 2020-09-11 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='full_description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
