# Generated by Django 3.0.7 on 2020-09-11 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200911_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
    ]
