# Generated by Django 3.0.7 on 2020-06-11 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=10)),
                ('issued_year', models.DateField(default=datetime.datetime.now)),
                ('photo_1', models.ImageField(blank=True, upload_to='cars')),
                ('photo_2', models.ImageField(blank=True, upload_to='cars')),
                ('photo_3', models.ImageField(blank=True, upload_to='cars')),
                ('photo_4', models.ImageField(blank=True, upload_to='cars')),
                ('photo_5', models.ImageField(blank=True, upload_to='cars')),
                ('photo_6', models.ImageField(blank=True, upload_to='cars')),
                ('is_published', models.BooleanField(default=True)),
                ('barnd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.CarModel')),
            ],
        ),
    ]
