# Generated by Django 3.0.7 on 2020-07-02 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200614_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damage_excess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='price_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='price_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('WG', 'Farmari'), ('SV', 'SUV'), ('HB', 'Viistoperä'), ('SD', 'Porrasperä')], default='WG', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('DI', 'Diesel'), ('PE', 'Bensiini'), ('EL', 'Sähkö'), ('HY', 'Hybridi')], default='PE', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AU', 'Automaatti'), ('MN', 'Manuaalli')], default='MN', max_length=10),
        ),
    ]
