# Generated by Django 3.0.7 on 2020-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BK', 'Musta'), ('WT', 'Valkoinen'), ('MT', 'Metalli')], default='WT', max_length=20),
        ),
    ]
