# Generated by Django 3.0.7 on 2020-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('PC', 'Henkilöauto'), ('VN', 'Pakettiauto'), ('MB', 'Minibussi')], default='VN', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BK', 'Musta'), ('WT', 'Valkoinen'), ('MT', 'Metalli/Harma')], default='WT', max_length=20),
        ),
    ]
