# Generated by Django 3.0.7 on 2020-07-21 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20200707_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('', 'Korimalli'), ('SV', 'SUV'), ('HB', 'Viistoperä'), ('SD', 'Porrasperä')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('', 'Tyyppi'), ('PC', 'Henkilöauto'), ('VN', 'Pakettiauto'), ('MB', 'Minibussi')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('', 'Väri'), ('BK', 'Musta'), ('WT', 'Valkoinen'), ('MT', 'Metalli/Harma')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('', 'Poltoaine'), ('DI', 'Diesel'), ('PE', 'Bensiini'), ('EL', 'Sähkö'), ('HY', 'Hybridi')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('', 'Vaihteisto'), ('AU', 'Automaatti'), ('MN', 'Manuaalli')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='use_purpose',
            field=models.CharField(choices=[('', 'Käytä tarkoitus'), ('PR', 'Omaan käyttöön'), ('TX', 'Taxi')], default='', max_length=10),
        ),
    ]
