# Generated by Django 3.0.7 on 2020-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20200721_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='use_purpose',
            field=models.CharField(choices=[('', 'Käyttötarkoitus'), ('PR', 'Omaan käyttöön'), ('TX', 'Taxi')], default='', max_length=10),
        ),
    ]
